sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g gulp
  - npm i codecov.io
install:
  - npm i --ignore-scripts
before_script:
  - npm prune
after_success:
  - 'cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js'
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
